name: build
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check on Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install pipenv && pipenv sync --dev
      - run: pipenv run pyright
      - run: pipenv run black --check src
      - run: tail -n +2 tests/size_list.tsv| xargs -L 1 pipenv run python tests/size_check.py verify

    name: check on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -W clippy::nursery -A clippy::stable-sort-primitive

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        with:
          command: test
          args: --release --all-features
